### ISSUE TITLE
Corpus access

### ISSUE THREAD

**Issue by alvations** [pycantonese/pycantonese#1]
Dear Jackson, 

We are a group of NLP researchers who's interested in Chinese varieties. 
Could you advise us on how to gain access to Prof. Luke's corpus? 

Regards,
Liling

**Comment by JacksonLLee** [comment]
Dear Liling,

Prof. Luke's corpus has just been publicly released very recently. Accordingly, I've updated PyCantonese to incorporate it into the package -- see http://pycantonese.github.io/data.html for details

Best,
Jackson
