### ISSUE TITLE
Windows Installer for 2.0

### ISSUE THREAD

**Issue by Sc07713** [pycantonese/pycantonese#13]
Hi there,

Any chance for a windows installer?

**Comment by JacksonLLee** [comment]
Hi Scottie,

Installing PyCantonese on Windows is straightforward with `pip`, as long as you have Python (v3.4 or above) ready. (I'm trying to avoid maintaining multiple distributions/installations, so no standalone Windows installer at this point...)

On the command line (the Start menu --> "Run..." --> type "cmd" and enter), run this:

```
$ python -m pip install pycantonese
```

The command `python` points to the `python.exe` on your system. If `python` isn't readily recognized as a command, then replace it with something like `C:\Python34\python` (the path for your `python.exe`).

If for whatever reason the command line approach doesn't work, fire up the Python interpreter:

```python
>>> import pip
>>> pip.main(['install', 'pycantonese'])
```

**Comment by Sc07713** [comment]
thanks so much for that, finally got it working. :)

Kind Regards

Scott Mckennie
